@baseUrl = https://localhost:7256

@bookId = 5411c1af-0ac1-443e-ab1b-c21312258342

@memberId = 


###Get api/books
GET {{baseUrl}}/api/books


###Get by id  api/books/abc

GET {{baseUrl}}/api/books/{{bookId}}

###Post book  api/books

Post {{baseUrl}}/api/books
content-type : application/json
{
  "title": "Clean Architecture222",
  "author": "Robert Martin222",
  "isbn": "9780134494166222",
  "genre": "Software Engineering222",
  "price": 50222,
  "publishedYear": 2017
}

### Update book
PUT {{baseUrl}}/api/books/{{bookId}}
Content-Type: application/json

{
  "title": "Clean Architecture Updated",
  "author": "Robert Martin",
  "genre": "Programming",
  "price": 60,
  "publishedYear": 2024
}

### Delete book
DELETE {{baseUrl}}/api/books/{{bookId}}



### Create Member
POST {{baseUrl}}/api/members
Content-Type: application/json

{
  "fullName": "Fatma Hassan",
  "email": "fatma@example.com",
  "phone": "01012345678",
  "address": "Ismailia"
}

### Get All Members
GET {{baseUrl}}/api/members


### Get Member By Id
GET {{baseUrl}}/api/members/{{memberId}}


### Update Member
PUT {{baseUrl}}/api/members/{{memberId}}
Content-Type: application/json

{
  "fullName": "Fatma Hassan Updated",
  "email": "fatma.updated@example.com",
  "phone": "01111111111",
  "address": "Cairo"
}

### Delete Member
DELETE {{baseUrl}}/api/members/{{memberId}}


